### ISSUE TITLE
Transaction fail when customer checkout with creditcard stored in Salesforce with CSE 

### ISSUE THREAD

**Issue by neotitan** [Adyen/adyen-salesforce-commerce-cloud#134]
This is a bug.

If customer pick a pre-saved credit card (saved in Salesforce not Adyen) and with CSE enabled, the transaction will always fail.

That's because CSE encryption doesn't encrypt Card Number and Card Holder if the card is stored in Salesforce. And Card Number and Card Holder are not included in 'card' object when making authorize request.

Fix in AdyenHelper.ds, starting line #189

 if (__AdyenHelper.getAdyenCseEnabled() && !empty(encryptedData)) {
                    cardObject['additionalData'] = {
                        'card.encrypted.json': encryptedData
                    };
                    // card was picked from stored cc card, thus card number and owner are not encrypted
                    if (card.selectedCardID.value) {
                        cardObject['card'] = {
                            'number': card.number.value,
                            'holderName': card.owner.value
                        };
                    }
                } else {
            		cardObject['card'] = {
                        'number': card.number.value,
                        'expiryMonth': card.month.value,
                        'expiryYear': card.year.value,
                        'cvc': card.cvn.value,
                        'holderName': card.owner.value
            		};
                }
                break;

**Comment by maassenbas** [comment]
Hi @neotitan , 
With CSE the tokens will be stored on Adyen's side. These tokens will then be included in the subsequent payment request and do not need to be encrypted anymore. 
These tokens will also be retrieved from Adyen each time a shopper reach the checkout and he will be able to select his desired saved credit card details there. 
Could you check if you retrieve the tokens correctly from Adyen?

**Comment by neotitan** [comment]
Hi @maassenbas,
Yes the encryption token I acquired from Adyen is totally fine.  I think you are mixing CSE and Recurring Payments together. Are you suggesting that CSE will only work with Adyen Recurring Payments?

How about the situation that customers want to use their saved credit card (stored in SFCC before Adyen is enabled)? You know when customer select a pre-saved credit card the card numbers are masked which means CSE cannot see the full number at front-end and encryption won't include card number.

Also by looking at the comment in Adyen's code, it implies that Adyen have considered above situation. But it's not being considered thoroughly at a later stage.

<img width="622" alt="2019-03-27_10-06-01" src="https://user-images.githubusercontent.com/2516449/55041369-7625d800-5078-11e9-9674-e887b6ff869a.png">

**Comment by maassenbas** [comment]
Hi @neotitan , 

CSE will work for both Adyen Recurring Payment as well as normal credit card payments. 
However, since the existing saved card details in SFCC do not have a token within Adyen, these pre-saved cards (before Adyen) would not work that way. 
The shopper should validate a payment again, which would create the token on Adyen's side for future transactions.

Kind regards,
Bas Maassen

**Comment by maassenbas** [comment]
Hi @neotitan , 

Another option would be to migrate the tokens first to the Adyen platform. That way your tokens can be retrieved from Adyen during the checkout. 
In order to get your tokens migrated to Adyen, you can contact our support team (support@adyen.com) and they will provide you the necessary steps. 

Kind regards,
Bas Maassen
