### ISSUE TITLE
AdyenCSE display shipping form twice on SiteGenesis

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#158]
# Environment

* Adyen Payment 18.3.0
* SiteGenesis v104.1.3

# Setup

We have installed vanilla SiteGenesis and Adyen cartridge by following the documentation available here :  https://docs.adyen.com/plugins/salesforce-commerce-cloud/

# Issue

After following [Adyen online documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/customize-storefront-code/#templatesdefaultcheckoutbillingpaymentmethods-isml) about `templates/default/checkout/billing/paymentmethods.isml`, we face to an issue.

When CSE is enabled, shipping form is diplayed twice as described in the followed screenshot.
Is this an expected behavior ?

![image](https://user-images.githubusercontent.com/42732979/59864744-ccf53200-9387-11e9-9e1b-704190b8656f.png)

**Comment by maassenbas** [comment]
Hi @aduponchel , 

No, this is not expected behaviour. 
Could you please make sure that [this](https://docs.adyen.com/plugins/salesforce-commerce-cloud/customize-storefront-code/#templatesdefaultcheckoutbillingpaymentmethods-isml) part is updated correctly in your app_storefront_core code?

Thanks,
Bas Maassen
