### ISSUE TITLE
"THIS_SCRIPT" is not defined.

### ISSUE THREAD

**Issue by lykhouzov** [Adyen/adyen-salesforce-commerce-cloud#261]
We've got folowing fatal error on our SFCC instance
```
[2020-05-14 20:46:30.719 GMT] FATAL PipelineCallServlet|447546246|Sites-*-Site|Checkout-Begin|PipelineCall|LtfWNIzrLS custom.Adyen [] Adyen: ReferenceError: "THIS_SCRIPT" is not defined. in int_adyen_overlay/cartridge/scripts/adyenGetOriginKey.ds:47
```
so ti looks like it is missing definition of the variable like it's done in others files.

**Comment by maassenbas** [comment]
Hi @lykhouzov , 

Thanks for reaching out.

Yes, we are aware of this. 
The "THIS_SCRIPT" variable is regarding the pipeline integration, which we do not support anymore in the cartridge. 
We have fixed this in our upcoming release.

For now, it looks like you have an error retrieving your OriginKey. 
In order to retrieve the correct OriginKey, you will have to configure the API key in your Custom Preferences. 
Could you make sure you have the right API key configured there? 
This should solve your issue.

Kind regards,
Bas Maassen
Adyen

**Comment by lykhouzov** [comment]
Hi @maassenbas 
thank you for response.
Good to know that it will be fixed in next release.
I will make sure that we have correct API Key.

Thank you.

**Comment by maassenbas** [comment]
Hi @lykhouzov ,
The code is now being reviewed and certified by Salesforce.
Once this is approved, we will release it. 
I think somewhere next week.

Kind regards,
Bas Maassen
Adyen
