### ISSUE TITLE
Paypal window pop-up and disappear without letting transaction happened (smart button)

### ISSUE THREAD

**Issue by wilsonwlam** [Adyen/adyen-salesforce-commerce-cloud#420]
**Describe the bug**
When select Paypal (smart button) as payment method in Salesforces commerce cloud (with Adyen plugin 20.1.2), the paypal pop-up window appear, showing the loading icon, and then disappear without complete the loading nor allowing any interaction.  The payment cannot get through and the order cannot complete.

**To Reproduce**
1. Add product to shopping cart
2. Checkout shopping cart
3. Enter all shipping and billing information
4. Click on Paypal smart button

**Expected behavior**
The paypal pop-up window show up, loaded completed and allow customer to login their paypal account, allow the authorisation and then close the pop-up window, bring back to SFCC and show the order completion page.

**Screenshots**

https://user-images.githubusercontent.com/53218741/107210715-7d251c00-6a3f-11eb-97e9-f70baadd2202.mov

**Desktop (please complete the following information):**
 - OS: iOS
 - Chrome Version 88.0.4324.96 (Official Build) (x86_64)

**Additional context**

**Comment by zaiddreakh** [comment]
Hi Wilson,

I had a look at the storefront you have provided to my colleagues in support.
![Screen Shot 2021-02-08 at 1 51 29 PM](https://user-images.githubusercontent.com/13759889/107222506-4c2ff180-6a15-11eb-83d1-576ac29f2671.png)

In the console here it says the problem is the mismatch in intent. The default value for intent we had in the cartridge is capture 
https://docs.adyen.com/payment-methods/paypal/web-component#show-paypal-in-your-payment-form
