### ISSUE TITLE
Cannot call method "toString" of null in int_adyen_overlay/cartridge/scripts/util/AdyenHelper.ds:749

### ISSUE THREAD

**Issue by TGManeh** [Adyen/adyen-salesforce-commerce-cloud#421]
**Describe the bug**
When a Product Bundle is added to the cart and all the needed information is filled in the required fields for the checkout, the next step is the "Place Order" button. Right on that moment, when the order is placed the bug appears and it is not possible to make the purchase.

**To Reproduce**
1. Create a Product Bundle
2. Place it in the cart
3. Go through checkout and select Credit card (Credit Visa 4111 1111 4555 1142 , 10/30,  737(cvc) )
4. See the error in the logs

**Expected behavior**
Should be able purchase the product without any interruption

**Desktop (please complete the following information):**
 - Browser - chrome
 - Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**
**Adyen version 19.2.2**
Error message 
error processing creditCard. Error message: Cannot call method "toString" of null more details: TypeError: Cannot call method "toString" of null in int_adyen_overlay/cartridge/scripts/util/AdyenHelper.ds:749

**Comment by ismailnguyen** [comment]
We also have this issue when we have a product bundle on the cart.
The issue is happening for all payment methods just before the payment request is made, while constructing the risk datas (https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_overlay/cartridge/scripts/util/riskDataHelper.js#L10).

To get product lines for risk datas we should not use `getAllProductLineItems()` method but `getProductLineItems().`
Because the first one will get all products including the content of product bundle, et those product bundle content don't have price (only the bundle has a price). So when calculating the amount per item of a product which doesn't have a price neither a currency an exception is thrown on AdyenHelper on method getCurrencyValueForApi:
`var currencyCode = dwutil.Currency.getCurrency(amount.currencyCode);
var digitsNumber = adyenHelperObj.getFractionDigits(currencyCode.toString());`

the first line will try to get a currency code from a product which doesn't have a currency (because it is a bundle content) so currencyCode will be `null`, and one the second line toString() of null will be rejected.

**Comment by TGManeh** [comment]
@ismailnguyen yes, exactly. I have the same result after debugging.

**Comment by maassenbas** [comment]
Thanks for your input @ismailnguyen and @TGManeh.
I was able to reproduce this and have a fix included in the upcoming release.

Kind regards,
Bas Maassen
Adyen
