### ISSUE TITLE
GetPaymentMethods uses first shipment to determine country

### ISSUE THREAD

**Issue by taurgis** [Adyen/adyen-salesforce-commerce-cloud#444]
**Describe the bug**
Current, the following code is executed to show the payment methods in the storefront:

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/75a405cafb9bea08d221d52aecdbc2ae9594f45d/src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/getPaymentMethod/utils.js#L16

This code looks at the first shipment to determine which payment methods to show, but this does not make sense. If you are in Belgium and want to ship to Germany, you want to see Belgian payment methods and not German payment methods.

**To Reproduce**
1. Be in an en_US shop
2. Select a shipping address in Germany
3. See only the German payment methods

**Expected behavior**
It is expected to see en_US payment methods.

**Comment by taurgis** [comment]
This also does not make sense in a multi-shipment environment. In our project, we allow multiple shipments.

**Comment by maassenbas** [comment]
Hi @taurgis ,

This is included by design as the first step in the default checkout is the shipping address.
Based on the selected country, we will retrieve the payment methods from Adyen. 
If there is multi shipment enabled, it would retrieve the country from the first/default shipping address.

Kind regards,
Bas Maassen
Adyen
