### ISSUE TITLE
transpile is not adding .project and not removing src/cartridge

### ISSUE THREAD

**Issue by BerkanCetinkayaOSF** [Adyen/adyen-salesforce-commerce-cloud#453]
**Describe the bug**
npm run transpile is not adding .project to compiled cartridges

**To Reproduce**
1. run the following commands first, npm install, npm run transpile
.project is not moved to compiled cartridges

Example .project: https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_SFRA/.project
2.  src/cartridges are not removed

since src/cartridges have .project, when we try to upload files. It's uploading from src/cartridges instead of cartridges.

**Expected behavior**
.project should be moved to compiled cartridges
src/cartridges should be removed only cartridges should be available

**Comment by maassenbas** [comment]
Hi @BerkanCetinkayaOSF ,
Thanks for raising this issue.
I will investigate this issue on my end and create a fix for it. 
I will let you know once we updated it.

Kind regards,
Bas Maassen
Adyen

**Comment by maassenbas** [comment]
Hi @BerkanCetinkayaOSF,

I investigated this issue further and was wondering why the `.project` file is required in the `cartridges` folder? 
Basically, the `npm run transpile` command will transpile the code from the `src` folder and generate the `cartridges` folder, which you will have to upload to the Business Manager. 
Since the `cartridges` folder will be on the root node, the `npm run uploadCartridge` command should upload that folder and not the `src/cartridges` folder. 
Could you please verify that on your end? 

Kind regards,
Bas Maassen
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
Hello @maassenbas ,

> I investigated this issue further and was wondering why the .project file is required in the cartridges folder?

I think I'm clear enough why we need .project
`since src/cartridges have .project, when we try to upload files. It's uploading from src/cartridges instead of cartridges.`

> Since the cartridges folder will be on the root node, the npm run uploadCartridge command should upload that folder and not the src/cartridges folder.
> Could you please verify that on your end?

You're making just assumptions or did you really try to upload files and did you check which one is uploaded?

I tried but `npm run uploadCartridge` and prophet upload vs code extension. For both same issue.

**Comment by BerkanCetinkayaOSF** [comment]
@maassenbas, can you please provide me an answer as soon as possible?

**Comment by BerkanCetinkayaOSF** [comment]
> @BerkanCetinkayaOSF ,
> The `.project` file is not required to use the `npm run uploadCartridge` command.
> I even tried reproducing your issue on my end, but everything seems to work fine.
> Can you make sure you are in the right directory? Potentially you can update the directory in your command to refer to the right path.

yes indeed, it's okay with npm run uploadCartridge command. but it's not okay with prophet uploader where most dev use it. Do you think to fix this issue?

**Comment by maassenbas** [comment]
Hi @BerkanCetinkayaOSF ,
Thanks for confirming that the `npm run uploadCartridge` command is working properly. 
We will create a ticket in our backlog for the prophet uploader, but will not prioritise this for now.

Kind regards,
Bas Maassen
Adyen

**Comment by mittinti** [comment]
@maassenbas , do you have any updates here ? this is really painful, I don't see the resolution for this yet. Internal dev teams would be blocked because of this issue. Please prioritize this asap.

**Comment by zaiddreakh** [comment]
Hey @mittinti,

Since our dev team doesn't use vscode or the prophet extension I'm afraid we still won't prioritise this issue for the near future, as we don't work with these tools. 
But I imagine as a workaround your dev team can create a simple script to add the .project file and include this script in the build process. 
If your team actually creates that script they can create a Pull Request here and we'll add it to the repo.

Regards,
Zaid
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
> @maassenbas , do you have any updates here ? this is really painful, I don't see the resolution for this yet. Internal dev teams would be blocked because of this issue. Please prioritize this asap.

the workaround, for now, is adding ".project " manually.
