### ISSUE TITLE
Disabling AdyenPos causes error on AdyenComponent

### ISSUE THREAD

**Issue by BerkanCetinkayaOSF** [Adyen/adyen-salesforce-commerce-cloud#455]
**Describe the bug**

**To Reproduce**
1. Disable AdyenPOS payment method from BM

**Expected behavior**
Only enabled AdyenComponent should be seen and AdyenPOS is hidden

**Actual behavior**
AdyenComponent is hidden. There's 500 error on Adyen-GetPaymentMethods

ERROR PipelineCallServlet|218303422|Sites-Clos19_FR-Site|Checkout-Begin|PipelineCall|yYpIys2NTE custom.Adyen []  TypeError: Cannot read property "length" from undefined in int_adyen_overlay/cartridge/scripts/updateSavedCards.js:91
Mon, 03 May 2021 13:39:45 GMT
ERROR PipelineCallServlet|1832929643|Sites-Clos19_FR-Site|Adyen-GetPaymentMethods|PipelineCall|yYpIys2NTE custom []  Error while executing script 'int_adyen_SFRA/cartridge/controllers/Adyen.js': SyntaxError: Unexpected token: o (int_adyen_SFRA/cartridge/controllers/Adyen.js#549)
	at int_adyen_SFRA/cartridge/controllers/Adyen.js:549
	at modules/server/route.js:85 (next)
	at modules/server/middleware.js:42 (https)
	at modules/server/route.js:85 (next)
	at modules/server/middleware.js:12 (get)
	at modules/server/route.js:93

**Comment by zaiddreakh** [comment]
Hey @BerkanCetinkayaOSF,

I believe it could be due to the `json.parse` in here https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/20.1.3/src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js#L778
If you change it from `AdyenConnectedTerminals: JSON.parse(connectedTerminals),`
to `AdyenConnectedTerminals: connectedTerminals,`
Thanks for pointing it out.

Regards,
Zaid
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
Thanks, @zaiddreakh, do you think to fix this issue?

**Comment by BerkanCetinkayaOSF** [comment]
@zaiddreakh , any updates here?

**Comment by wboereboom** [comment]
Hi @BerkanCetinkayaOSF,
This issue should be resolved from here on out. The snippet below is from our release candidate, which should go live soon. This ensures the default response returns a parseable JSON instead of an empty object.
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/b8c7fbaf9f035173838ed75e41cf7f52a883786d/src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/getPaymentMethod/utils.js#L25-L30

Apologies for the tardy response, and I hope this resolves your issue.

Regards,
Wouter
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
Hello @wboereboom , for now we make METHOD_ADYEN_POS hidden in the template so that not possible to use it but we'll use this fix for sure, thanks
