### ISSUE TITLE
JSON object of `orderModel` stored in `Adyen_CustomerEmail` attribute

### ISSUE THREAD

**Issue by ta-benhon** [Adyen/adyen-salesforce-commerce-cloud#669]
**Describe the bug**
JSON object of `orderModel` stored in `order.custom.Adyen_CustomerEmail` attribute in various locations in the code base.

**To Reproduce**
An example of this code line can be found here: https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/main/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/showConfirmation/order.js#L18

**Expected behavior**
Either the customer email is to be stored in the order's custom attribute or a separate custom attribute to store the order model information.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 101.0.1

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version N/A

**Additional context**
The expected behaviour is not entirely necessary to be applied if a justified clarification can be found why the order model is stored in the `CustomerEmail` custom attribute.

Thanks in advance.

**Comment by ta-benhon** [comment]
Further contact with our Adyen technical lead concluded this variable contains order data for email purposes. 

I would also like to note, this `Adyen_CustomerEmail` came to our attention due to a character limit on our middleware system ingesting the order XMLs.

**Comment by wboereboom** [comment]
Hi @ta-benhon,

Thanks for raising this issue, and apologies for the lack of response on our side.
I'm glad to hear your technical contact was able to clear up the confusion about the field's purpose.

However the character limit is still reason for concern.

Can you produce a scenario which reproduces this issue so that we may look into this error?

Thank you for your patience, and we'll try to be more forthcoming in responding to GitHub issuers going forward.

Kind Regards,
Wouter
Adyen

**Comment by zaiddreakh** [comment]
stale
