### ISSUE TITLE
holderName validation issue

### ISSUE THREAD

**Issue by daniel-delatorre-xplore** [Adyen/adyen-salesforce-commerce-cloud#701]
**Describe the bug**
we are migrating to the Adyen version 21.2.0 however we are having issues with the card holderName field. When we submit the payment form without the card holderName we are receiving this error:
![image](https://user-images.githubusercontent.com/57527110/191059959-5f837adc-fc9c-4abc-9a8b-3f5b8680f8df.png)

**To Reproduce**

**Expected behavior**
I would expect an error label shown here
![image](https://user-images.githubusercontent.com/57527110/191060182-05941493-0d33-41ef-96ea-11f704dd004a.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wboereboom** [comment]
hi @daniel-delatorre-xplore ,

Unfortunately this is an issue with the Adyen Web Component we are using in version 21.2.0.
This issue has been fixed in version 22.1.0.
Starting version 22.x.x we have also introduced to easily upgrade the web component version bugs on the component can be 'hotfixed' by devs like you going forward.

If upgrading is not an option right now I recommend to update your isml templates with the changes from #636. 
After this you can easily upgrade the component version by changing `CHECKOUT_COMPONENT_VERSION` in `src/cartridges/int_adyen_overlay/cartridge/scripts/util/adyenHelper.js`

Kind Regards,
Wouter
Adyen
